name: simple_deployment_pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: |
          npm install --prefix client && npm install --prefix server

      - name: Lint Code
        run: |
          npm run lint --prefix client && npm run lint --prefix server

      - name: Build Applications
        run: |
          npm run build --prefix client && npm run build --prefix server

      - name: Run tests on client
        run: |
          npm run test --prefix client && npm run test --prefix server
