name: Deployment pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies (Client)
        run: |
          cd client && npm install

      - name: Install dependencies (Server)
        run: |
          cd server && npm install

      - name: Run Eslint on Client
        run: |
          cd client && npm run lint

      # - name: Run Eslint on Server
      #   run: |
      #     cd server && npm run lint
      - name: Build client
        run: |
          cd client && npm run build
